// <auto-generated />
using System;
using GastroGestion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GastroGestion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GastroGestionDbContext))]
    [Migration("20260623023143_AddFacturaAnulacion")]
    partial class AddFacturaAnulacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GastroGestion.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CondicionIVA")
                        .HasColumnType("int");

                    b.Property<string>("Cuit")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("NumeroCliente")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique()
                        .HasFilter("[Cuit] IS NOT NULL");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("GastroGestion.Domain.Facturacion.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CAE")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PedidosFacturados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PedidosFacturados");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("VencimientoCAE")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("GastroGestion.Domain.Ingredientes.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<int>("UnidadBase")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Ingredientes", (string)null);
                });

            modelBuilder.Entity("GastroGestion.Domain.Menus.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaVigencia")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Menus", (string)null);
                });

            modelBuilder.Entity("GastroGestion.Domain.Mesas.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid?>("PedidoActivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Mesas", (string)null);
                });

            modelBuilder.Entity("GastroGestion.Domain.Pedidos.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<Guid?>("MesaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("GastroGestion.Domain.Platos.Plato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AlicuotaIVA")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Platos", (string)null);
                });

            modelBuilder.Entity("GastroGestion.Domain.Proveedores.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cuit")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique()
                        .HasFilter("[Cuit] IS NOT NULL");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("GastroGestion.Domain.Stock.MovimientoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LineaPedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrdenTrabajoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.ToTable("MovimientosStock", (string)null);
                });

            modelBuilder.Entity("GastroGestion.Domain.Clientes.Cliente", b =>
                {
                    b.OwnsMany("GastroGestion.Domain.Clientes.Direccion", "Direcciones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Departamento")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Piso")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("ClienteId");

                            b1.ToTable("ClienteDirecciones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("GastroGestion.Domain.Facturacion.Factura", b =>
                {
                    b.OwnsMany("GastroGestion.Domain.Facturacion.FacturaLinea", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Cantidad")
                                .HasColumnType("int");

                            b1.Property<Guid>("FacturaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IVA")
                                .HasColumnType("int")
                                .HasColumnName("IVA_Alicuota");

                            b1.Property<Guid>("LineaPedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("FacturaId");

                            b1.ToTable("FacturaLineas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FacturaId");

                            b1.OwnsOne("GastroGestion.Domain.ValueObjects.Dinero", "PrecioUnitario", b2 =>
                                {
                                    b2.Property<Guid>("FacturaLineaId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Moneda")
                                        .HasColumnType("int")
                                        .HasColumnName("PrecioUnitario_Moneda");

                                    b2.Property<decimal>("Monto")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("PrecioUnitario_Monto");

                                    b2.HasKey("FacturaLineaId");

                                    b2.ToTable("FacturaLineas");

                                    b2.WithOwner()
                                        .HasForeignKey("FacturaLineaId");
                                });

                            b1.Navigation("PrecioUnitario")
                                .IsRequired();
                        });

                    b.OwnsMany("GastroGestion.Domain.Facturacion.Pago", "Pagos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("FacturaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("FechaPago")
                                .HasColumnType("datetime2");

                            b1.Property<int>("MetodoPago")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("FacturaId");

                            b1.ToTable("FacturaPagos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FacturaId");

                            b1.OwnsOne("GastroGestion.Domain.ValueObjects.Dinero", "Monto", b2 =>
                                {
                                    b2.Property<Guid>("PagoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Moneda")
                                        .HasColumnType("int")
                                        .HasColumnName("Monto_Moneda");

                                    b2.Property<decimal>("Monto")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Monto_Monto");

                                    b2.HasKey("PagoId");

                                    b2.ToTable("FacturaPagos");

                                    b2.WithOwner()
                                        .HasForeignKey("PagoId");
                                });

                            b1.Navigation("Monto")
                                .IsRequired();
                        });

                    b.Navigation("Lineas");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("GastroGestion.Domain.Menus.Menu", b =>
                {
                    b.OwnsMany("GastroGestion.Domain.Menus.MenuItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MenuId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PlatoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("MenuId");

                            b1.ToTable("MenuItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MenuId");

                            b1.OwnsOne("GastroGestion.Domain.ValueObjects.Dinero", "PrecioOverride", b2 =>
                                {
                                    b2.Property<Guid>("MenuItemId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Moneda")
                                        .HasColumnType("int")
                                        .HasColumnName("PrecioOverride_Moneda");

                                    b2.Property<decimal>("Monto")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("PrecioOverride_Monto");

                                    b2.HasKey("MenuItemId");

                                    b2.ToTable("MenuItems");

                                    b2.WithOwner()
                                        .HasForeignKey("MenuItemId");
                                });

                            b1.Navigation("PrecioOverride");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("GastroGestion.Domain.Pedidos.Pedido", b =>
                {
                    b.OwnsMany("GastroGestion.Domain.Pedidos.LineaPedido", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Cantidad")
                                .HasColumnType("int");

                            b1.Property<int?>("IVA")
                                .HasColumnType("int")
                                .HasColumnName("IVA_Alicuota");

                            b1.Property<string>("Observaciones")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PlatoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("PrecioConfirmado")
                                .HasColumnType("bit")
                                .HasColumnName("PrecioConfirmado");

                            b1.HasKey("Id");

                            b1.HasIndex("PedidoId");

                            b1.ToTable("PedidoLineas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");

                            b1.OwnsOne("GastroGestion.Domain.ValueObjects.Dinero", "PrecioUnitario", b2 =>
                                {
                                    b2.Property<Guid>("LineaPedidoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Moneda")
                                        .HasColumnType("int")
                                        .HasColumnName("PrecioUnitario_Moneda");

                                    b2.Property<decimal>("Monto")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("PrecioUnitario_Monto");

                                    b2.HasKey("LineaPedidoId");

                                    b2.ToTable("PedidoLineas");

                                    b2.WithOwner()
                                        .HasForeignKey("LineaPedidoId");
                                });

                            b1.Navigation("PrecioUnitario");
                        });

                    b.OwnsMany("GastroGestion.Domain.Pedidos.OrdenTrabajo", "OrdenesTrabajo", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("CocineroAsignado")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CocineroAsignado");

                            b1.Property<int>("Estado")
                                .HasColumnType("int");

                            b1.Property<Guid>("LineaPedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PlatoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("RecetaSnapshot")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("RecetaSnapshot");

                            b1.HasKey("Id");

                            b1.HasIndex("PedidoId");

                            b1.ToTable("PedidoOrdenesTrabajo", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.OwnsOne("GastroGestion.Domain.ValueObjects.DireccionEntrega", "DireccionEntrega", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Entrega_Calle");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Entrega_Ciudad");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Entrega_CodigoPostal");

                            b1.Property<string>("Departamento")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Entrega_Departamento");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Entrega_Numero");

                            b1.Property<string>("Piso")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Entrega_Piso");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Entrega_Provincia");

                            b1.HasKey("PedidoId");

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.Navigation("DireccionEntrega");

                    b.Navigation("Lineas");

                    b.Navigation("OrdenesTrabajo");
                });

            modelBuilder.Entity("GastroGestion.Domain.Platos.Plato", b =>
                {
                    b.OwnsMany("GastroGestion.Domain.Platos.LineaReceta", "LineasReceta", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("IngredienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PlatoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("PlatoReferenciadoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PlatoId");

                            b1.ToTable("PlatoLineasReceta", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PlatoId");

                            b1.OwnsOne("GastroGestion.Domain.ValueObjects.Cantidad", "Cantidad", b2 =>
                                {
                                    b2.Property<Guid>("LineaRecetaId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Unidad")
                                        .HasColumnType("int")
                                        .HasColumnName("Cantidad_Unidad");

                                    b2.Property<decimal>("Valor")
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("Cantidad_Valor");

                                    b2.HasKey("LineaRecetaId");

                                    b2.ToTable("PlatoLineasReceta");

                                    b2.WithOwner()
                                        .HasForeignKey("LineaRecetaId");
                                });

                            b1.Navigation("Cantidad")
                                .IsRequired();
                        });

                    b.OwnsOne("GastroGestion.Domain.ValueObjects.Dinero", "PrecioBase", b1 =>
                        {
                            b1.Property<Guid>("PlatoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Moneda")
                                .HasColumnType("int")
                                .HasColumnName("PrecioBase_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecioBase_Monto");

                            b1.HasKey("PlatoId");

                            b1.ToTable("Platos");

                            b1.WithOwner()
                                .HasForeignKey("PlatoId");
                        });

                    b.Navigation("LineasReceta");

                    b.Navigation("PrecioBase")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
